### ISSUE TITLE
NaN occurs during training

### ISSUE THREAD

**Issue by kaixin96** [pokaxpoka/netrand#1]
Hi @pokaxpoka , thanks for your great work. I am trying to reimplement it but facing NaN issues. Can you help give some implementation suggestions? Thanks very much.

After certain training steps (it is random, sometimes the issue does not occur), `policy_entropy` suddenly becomes NaN. In the next step, other training statistics are affected and also become NaN, crashing the training.

Specifically, may I ask how you implement the synchronization of randomization parameter phi across different MPI process?

Many thanks and best regards!

**Comment by kibok90** [comment]
Hi @kaixin96, thanks for your interest. Did you use Xavier normal distribution when re-initializing your random layer?

Regarding the implementation, for example, in our coinrun experiment, we specifically added the random layer in
https://github.com/openai/coinrun/blob/master/coinrun/policies.py#L67
and re-initialized in
https://github.com/openai/coinrun/blob/master/coinrun/ppo2.py#L303
so we didn't worry about the MPI process.

**Comment by kaixin96** [comment]
Thanks for your reply.

If the random layer is added in https://github.com/openai/coinrun/blob/master/coinrun/policies.py#L67, in my understanding, each worker will use different random projection weights. Is that the planned behavior?

Also, it would be great if you could upload some core parts (model, policy, runner) of your code. Thank you very much.

Best regards

**Comment by kaixin96** [comment]
I have another question: after the random conv layer, did you rescale the output to [0, 1] before feeding it to the impala network? Thank you.

**Comment by kibok90** [comment]
each worker will use different random projection weights
-> Yes. I think using shared parameters for the random layer for all workers is also fine though.

upload some core parts
-> I just uploaded code for replicating the coinrun experiment in our paper.

did you rescale the output to [0, 1] before feeding it to the impala network
-> No we didn't.

**Comment by kaixin96** [comment]
Thanks for your quick reply. I will check out your code and try to locate the cause of NaN.

Please leave this issue open. I will add my debugging results later, in case someone else also comes across this problem.

**Comment by kaixin96** [comment]
It turns out I used wrong loss and didn't stop the gradient.
